### ISSUE TITLE
"Visando a aumentar" é muito feio

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [BrunoGomesCoelho/OrgComputadoresAmnesia#1]
Galera, o Cruz insiste no uso dessa expressão retrograda. O que acham de mudarmos para:
"Visando aumentar"?

PS: democracia wins cruz

**Comment by gmelodie** [comment]
Concordo com o seu ponto de vista mas infelizmente quem manda nessa porra aqui sou eu

**Comment by BrunoGomesCoelho** [comment]
Eu que posso tirar de colaborador.

**Comment by gmelodie** [comment]
🥇
